Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [golang/try/x_oscar-go1.21-darwin-amd64_14](https://cr-buildbucket.appspot.com/build/8742959535143953473) has failed with summary ([view all results](https://go-review.googlesource.com/c/597147?checksPatchset=1&tab=checks)):

---
* go on release-branch.go1.21 ([commit 12e9b96](https://go.googlesource.com/go/+/12e9b968bc8890b072b98facbd079ca337bd33a0))
* oscar on master ([change 597147](https://go-review.googlesource.com/c/oscar/+/597147/1))

Error: `Failed to run "fetch \"golang.org/x/oscar\" dependencies": exit status 1`

Additional links for debugging:

Patch-set: 1
Tag: autogenerated:cq:dry-run:1720461051
Attention: {"person_ident":"Gerrit User 5056 \u003c5056@62eb7196-b449-3ce5-99f1-c037f21e1705\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}