Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Failed Tryjobs:
* [golang/try/x_oscar-go1.21-linux-amd64](https://cr-buildbucket.appspot.com/build/8742959521852948033). Summary ([view all results](https://go-review.googlesource.com/c/597144?checksPatchset=1&tab=checks)):

---
* go on release-branch.go1.21 ([commit 12e9b96](https://go.googlesource.com/go/+/12e9b968bc8890b072b98facbd079ca337bd33a0))
* oscar on master ([change 597144](https://go-review.googlesource.com/c/oscar/+/597144/1))

Error: `Failed to run "fetch \"golang.org/x/oscar\" dependencies": exit status 1`

Additional links for debugging:


---
* [golang/try/x_oscar-go1.22-linux-amd64](https://cr-buildbucket.appspot.com/build/8742959521852947985). Summary ([view all results](https://go-review.googlesource.com/c/597144?checksPatchset=1&tab=checks)):

---
* go on release-branch.go1.22 ([commit 8e1fdea](https://go.googlesource.com/go/+/8e1fdea8316d840fd07e9d6e026048e53290948b))
* oscar on master ([change 597144](https://go-review.googlesource.com/c/oscar/+/597144/1))

Error: `Failed to run "fetch \"golang.org/x/oscar\" dependencies": exit status 1`

Additional links for debugging:


---

Patch-set: 1
Tag: autogenerated:cq:dry-run:1720461058
Attention: {"person_ident":"Gerrit User 5056 \u003c5056@62eb7196-b449-3ce5-99f1-c037f21e1705\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}