Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [golang/try/x_oscar-go1.22-darwin-amd64_14](https://cr-buildbucket.appspot.com/build/8742959534548544129) has failed with summary ([view all results](https://go-review.googlesource.com/c/597145?checksPatchset=1&tab=checks)):

---
* go on release-branch.go1.22 ([commit 8e1fdea](https://go.googlesource.com/go/+/8e1fdea8316d840fd07e9d6e026048e53290948b))
* oscar on master ([change 597145](https://go-review.googlesource.com/c/oscar/+/597145/1))

Error: `Failed to run "fetch \"golang.org/x/oscar\" dependencies": exit status 1`

Additional links for debugging:

Patch-set: 1
Tag: autogenerated:cq:dry-run:1720461053
Attention: {"person_ident":"Gerrit User 5056 \u003c5056@62eb7196-b449-3ce5-99f1-c037f21e1705\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}