Update patch set 2
Patch Set 2:

This CL has failed the run. Reason:

Failed Tryjobs:
* [golang/try/x_oscar-gotip-linux-amd64](https://cr-buildbucket.appspot.com/build/8742885767520059937). Summary ([view all results](https://go-review.googlesource.com/c/597138?checksPatchset=2&tab=checks)):

---
* go on master ([commit 87ec2c9](https://go.googlesource.com/go/+/87ec2c959c73e62bfae230ef7efca11ec2a90804))
* oscar on master ([change 597138](https://go-review.googlesource.com/c/oscar/+/597138/2))

Error: `Failed to run "fetch \"golang.org/x/oscar\" dependencies": exit status 1`

Additional links for debugging:


---
* [golang/try/x_oscar-gotip-windows-amd64](https://cr-buildbucket.appspot.com/build/8742885767520059873). Summary ([view all results](https://go-review.googlesource.com/c/597138?checksPatchset=2&tab=checks)):

---
* go on master ([commit 87ec2c9](https://go.googlesource.com/go/+/87ec2c959c73e62bfae230ef7efca11ec2a90804))
* oscar on master ([change 597138](https://go-review.googlesource.com/c/oscar/+/597138/2))

Error: `Failed to run "fetch \"golang.org/x/oscar\" dependencies": exit status 1`

Additional links for debugging:


---

Patch-set: 2
Tag: autogenerated:cq:dry-run:1720531409
Attention: {"person_ident":"Gerrit User 5056 \u003c5056@62eb7196-b449-3ce5-99f1-c037f21e1705\u003e","operation":"ADD","reason":"ps#2: Tryjobs failed"}