Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Failed Tryjobs:
* [golang/try/x_oscar-go1.21-linux-amd64](https://cr-buildbucket.appspot.com/build/8742959530120594737). Summary ([view all results](https://go-review.googlesource.com/c/597135?checksPatchset=1&tab=checks)):

---
* go on release-branch.go1.21 ([commit 12e9b96](https://go.googlesource.com/go/+/12e9b968bc8890b072b98facbd079ca337bd33a0))
* oscar on master ([change 597135](https://go-review.googlesource.com/c/oscar/+/597135/1))

Error: `Failed to run "fetch \"golang.org/x/oscar\" dependencies": exit status 1`

Additional links for debugging:


---
* [golang/try/x_oscar-gotip-linux-amd64-boringcrypto](https://cr-buildbucket.appspot.com/build/8742959530120594593). Summary ([view all results](https://go-review.googlesource.com/c/597135?checksPatchset=1&tab=checks)):

---
* go on master ([commit 6d89b38](https://go.googlesource.com/go/+/6d89b38ed86e0bfa0ddaba08dc4071e6bb300eea))
* oscar on master ([change 597135](https://go-review.googlesource.com/c/oscar/+/597135/1))

Error: `Failed to run "fetch \"golang.org/x/oscar\" dependencies": exit status 1`

Additional links for debugging:


---

Patch-set: 1
Tag: autogenerated:cq:dry-run:1720461060
Attention: {"person_ident":"Gerrit User 5056 \u003c5056@62eb7196-b449-3ce5-99f1-c037f21e1705\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}