Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [golang/try/x_oscar-gotip-linux-amd64-boringcrypto](https://cr-buildbucket.appspot.com/build/8742959511738351921) has failed with summary ([view all results](https://go-review.googlesource.com/c/597150?checksPatchset=1&tab=checks)):

---
* go on master ([commit 6d89b38](https://go.googlesource.com/go/+/6d89b38ed86e0bfa0ddaba08dc4071e6bb300eea))
* oscar on master ([change 597150](https://go-review.googlesource.com/c/oscar/+/597150/1))

Error: `Failed to run "fetch \"golang.org/x/oscar\" dependencies": exit status 1`

Additional links for debugging:

Patch-set: 1
Tag: autogenerated:cq:dry-run:1720461065
Attention: {"person_ident":"Gerrit User 5056 \u003c5056@62eb7196-b449-3ce5-99f1-c037f21e1705\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}