Update patch set 1
Patch Set 1:

This CL has failed the run. Reason:

Tryjob [golang/try/x_oscar-gotip-linux-amd64](https://cr-buildbucket.appspot.com/build/8742959503382789777) has failed with summary ([view all results](https://go-review.googlesource.com/c/597152?checksPatchset=1&tab=checks)):

---
* go on master ([commit 6d89b38](https://go.googlesource.com/go/+/6d89b38ed86e0bfa0ddaba08dc4071e6bb300eea))
* oscar on master ([change 597152](https://go-review.googlesource.com/c/oscar/+/597152/1))

Error: `Failed to run "fetch \"golang.org/x/oscar\" dependencies": exit status 1`

Additional links for debugging:

Patch-set: 1
Tag: autogenerated:cq:dry-run:1720461071
Attention: {"person_ident":"Gerrit User 5056 \u003c5056@62eb7196-b449-3ce5-99f1-c037f21e1705\u003e","operation":"ADD","reason":"ps#1: Tryjobs failed"}